%  Build script for "psfFit.m". 
clear mex % so that we can overwrite the mexw64/mexa64 files

disp('Building testceres')

% Note: compile with COMPFLAGS = "\D DEBUG ... " for debug output

% For static linking (no ceres.dll required, but big file, longer compilation time)
% mex LINKFLAGS="$LINKFLAGS /LIBPATH:ceres-windows\x64\Release libglog_static.lib ceres_static.lib " ...
%     COMPFLAGS="$COMPFLAGS ...
%     ... /D DEBUG ...
%     /D CERES_USING_STATIC_LIBRARY /D GOOGLE_GLOG_DLL_DECL= ...
%     /I ceres-windows\ceres-solver\include /I ceres-windows\win\include ...
%     /I ceres-windows\glog\src /I ceres-windows\glog\src\windows /I ceres-windows\eigen" ...
%     mx_psfFit.cpp

% For dynamic linking，-和\ 能互相替换 
mex LINKFLAGS="$LINKFLAGS -LIBPATH:ceres-windows\x64\Release ceres.lib libglog_static.lib" ...
    COMPFLAGS="$COMPFLAGS -Wall...
    ... /D DEBUG ...
    -DGOOGLE_GLOG_DLL_DECL= -Iceres-windows\ceres-solver\include -Iceres-windows\win\include ...
    -Iceres-windows\glog\src -Iceres-windows\glog\src\windows -Iceres-windows\eigen" ...
    -Iceres-windows\Eigen\ ceres_optimization.cpp pose_local_parameterization.cpp utility.cpp

% % dynamic linking 另一种mex方式,失败
% mex "$COMPFLAGS ...
%     ... /D DEBUG ...
%     /D GOOGLE_GLOG_DLL_DECL= ...
%     /I ceres-windows\ceres-solver\include /I ceres-windows\win\include ...
%     /I ceres-windows\glog\src /I ceres-windows\glog\src\windows /I ceres-windows\eigen" ...
%     -Lceres-windows\x64\Release -lceres -llibglog_static testceres.cpp 

copyfile('ceres-windows\x64\Release\ceres.dll','.')
% jf: LINKFLAGS 干嘛的， /libpath 指定了library的路径，但是为什么要在linkflags里面，不能直接I 或者 L
% 吗？https://ww2.mathworks.cn/matlabcentral/answers/99915-can-i-call-an-external-shared-library-dll-from-a-matlab-mex-file
% https://ww2.mathworks.cn/matlabcentral/answers/103012-how-can-i-call-a-dll-or-shared-library-function-using-mex-files-instead-of-the-generic-dll-shared
% /D 相当于 #define
